# ARM GCC Toolchain for Cortex-M0+ (STM32G0B1)
# Generated by Hardware2Code — used with: cmake -B build -DCMAKE_TOOLCHAIN_FILE=toolchain.cmake

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

# Find toolchain binaries
find_program(CMAKE_C_COMPILER   arm-none-eabi-gcc   REQUIRED)
find_program(CMAKE_ASM_COMPILER arm-none-eabi-gcc   REQUIRED)
find_program(CMAKE_CXX_COMPILER arm-none-eabi-g++   REQUIRED)
find_program(CMAKE_OBJCOPY      arm-none-eabi-objcopy REQUIRED)
find_program(CMAKE_OBJDUMP      arm-none-eabi-objdump REQUIRED)
find_program(CMAKE_SIZE_UTIL    arm-none-eabi-size   REQUIRED)

set(CMAKE_ASM_COMPILER_ARGS "-x assembler-with-cpp")

# No linking try-compile — targeting bare-metal
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

# Global compile flags
# -std=c99 is REQUIRED, not cosmetic: the project claims C99 / MISRA C:2012
# compliance, and without it the compiler defaults to a much newer standard
# (gcc 15 defaults to C23), so C99 conformance was never actually enforced.
set(CMAKE_C_FLAGS_INIT "-mcpu=cortex-m0plus -mthumb -std=c99 -fdata-sections -ffunction-sections -Wall -Wextra -Wno-unused-parameter")
set(CMAKE_ASM_FLAGS_INIT "-mcpu=cortex-m0plus -mthumb")

# Global linker flags
# -u _printf_float / -u _scanf_float: newlib-nano omits float support in
# printf/scanf by default.  Without them "%.1f" prints nothing useful and
# sscanf("%f") fails on target, while host tests (glibc) pass regardless.
# Costs roughly 6-10 KB of flash; drop them only if the firmware is known
# to use integer formatting exclusively.
set(CMAKE_EXE_LINKER_FLAGS_INIT "-mcpu=cortex-m0plus -mthumb -specs=nano.specs -specs=nosys.specs -Wl,--gc-sections -u _printf_float -u _scanf_float -Wl,-Map=${CMAKE_PROJECT_NAME}.map")
